<?php

define('PERMISSION_GET_LIST_BLOG_ID', 1);

define('PERMISSION_GET_BLOG_ID', 2);

define('PERMISSION_CREATE_BLOG_ID', 3);

define('PERMISSION_UPDATE_BLOG_ID', 4);

define('PERMISSION_DELETE_BLOG_ID', 5);

define('PERMISSION_UPLOAD_IMAGE_BLOG_ID', 6);
